startLoadingScreen ["","RscDisplayLoadCustom"];
cutText ["","BLACK OUT"];
enableSaving [false, false];
dayZ_instance =	11;
dayzHiveRequest = [];
initialized = false;
dayz_previousID = 0;
player setVariable ["BIS_noCoreConversations", true];
enableRadio true;
enableSentences false;
spawnShoremode = 1;
spawnArea= 1500;
dayz_paraSpawn = false;
dayz_fullMoonNights = false;
dayz_MapArea = 14000;
dayz_minpos = -1;
dayz_maxpos = 16000;
DZE_MissionLootTable = true;
MaxHeliCrashes= 5;
MaxVehicleLimit = 0;
MaxDynamicDebris = 0;
MaxMineVeins = 4;
MaxAmmoBoxes = 7;
dayz_maxZeds = 50;
dayz_maxLocalZombies = 5;
dayz_maxGlobalZombiesInit = 1;
dayz_maxGlobalZombiesIncrease = 2;
dayz_zedsAttackVehicles = true;
dayz_maxAnimals = 4;
dayz_tameDogs = true;
DZE_ConfigTrader = true;
dayz_sellDistance_vehicle = 40;
dayz_sellDistance_boat = 4;
dayz_sellDistance_air = 60;
DZE_R3F_WEIGHT = false;
DZE_PlayerZed = false;
DZE_BackpackGuard = true;
DZE_SelfTransfuse = true;
DZE_selfTransfuse_Values = [6000, 35, 300];
DZE_ForceNameTagsOff = true;
DZE_DeathMsgGlobal = true;
DZE_DeathMsgTitleText = true;
DZE_HeliLift = true;
DZE_AntiWallLimit = 3;
DynamicVehicleDamageLow = 0;
DynamicVehicleDamageHigh = 60;
DZE_StaticConstructionCount = 1;
DZE_BuildingLimit = 300;
DZE_requireplot = 0;
DZE_PlotPole = [100,210];
DZE_BuildOnRoads = true;
DZE_snapExtraRange = 0;
DZE_noRotate = [];
DZE_curPitch = 45;
WG_adminBuild = ["76561198041396167","76561198060680988","76561198011494379"];
EpochEvents = [["any","any","any","any",30,"crash_spawner"],["any","any","any","any",0,"crash_spawner"],["any","any","any","any",15,"supply_drop"],["any","any","any","any",10,"Military"],["any","any","any","any",25,"Treasure"],["any","any","any","any",35,"Construction"]];
call compile preprocessFileLineNumbers "custom\variables.sqf";
progressLoadingScreen 0.1;
call compile preprocessFileLineNumbers "\z\addons\dayz_code\init\publicEH.sqf";
progressLoadingScreen 0.2;
call compile preprocessFileLineNumbers "\z\addons\dayz_code\medical\setup_functions_med.sqf";
progressLoadingScreen 0.4;
call compile preprocessFileLineNumbers "custom\compiles.sqf";
progressLoadingScreen 0.5;
call compile preprocessFileLineNumbers "server_traders.sqf";
call compile preprocessFileLineNumbers "custom\logistic\init.sqf";
progressLoadingScreen 1.0;
"filmic" setToneMappingParams [0.153, 0.357, 0.231, 0.1573, 0.011, 3.750, 6, 4]; setToneMapping "Filmic";
if (isServer) then {
call compile preprocessFileLineNumbers "\z\addons\dayz_server\missions\DayZ_Epoch_11.Chernarus\dynamic_vehicle.sqf";
execVM "custom\treasure\ammobox.sqf";
_nil = [] execVM "\z\addons\dayz_server\missions\DayZ_Epoch_11.Chernarus\mission.sqf";
_serverMonitor = [] execVM "\z\addons\dayz_code\system\server_monitor.sqf";
};
if (!isDedicated) then {
ExecVM "custom\TradeFromVehicle\setup\init.sqf";
[] execVM "custom\misc\Server_WelcomeCredits.sqf";
0 fadeSound 0;
waitUntil {!isNil "dayz_loadScreenMsg"};
dayz_loadScreenMsg = (localize "STR_AUTHENTICATING");
_id = player addEventHandler ["Respawn", {_id = [] spawn player_death;}];
_playerMonitor = [] execVM "\z\addons\dayz_code\system\player_monitor.sqf";
execVM "custom\spawn\start.sqf";
execVM "custom\dzgm\init.sqf";
[] execVM "custom\safezone\init.sqf";
//[false,12] execVM "\z\addons\dayz_code\compile\local_lights_init.sqf";
execVM "custom\service_point\service_point.sqf";
_nil = [] execVM "custom\VehicleKeyChanger\VehicleKeyChanger_init.sqf";
execVM "custom\misc\GG_MapMarker.sqf";
};
//execVM "\z\addons\dayz_code\external\DynamicWeatherEffects.sqf";
#include "\z\addons\dayz_code\system\BIS_Effects\init.sqf"